[tools]
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:Kitware/CMake" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:Myriad-Dreamin/tinymist" = "latest"
"aqua:Orange-OpenSource/hurl" = "latest"
"aqua:abiosoft/colima" = "latest"
"aqua:astral-sh/ruff" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:docker/cli" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:pemistahl/grex" = "latest"
"aqua:schollz/croc" = "latest"
"aqua:sharkdp/hyperfine" = "latest"
"aqua:tldr-pages/tlrc" = "latest"
"aqua:tmux/tmux-builds" = "latest"
"aqua:watchexec/watchexec" = "latest"
"conda:chafa" = "latest"
"conda:clang-format" = "latest"
"conda:faker" = "latest"
"conda:gopls" = "latest"
"conda:htop" = "latest"
"conda:jrnl" = "latest"
"conda:pkgconf" = "latest"
"conda:stow" = "latest"
"conda:ttyd" = "latest"
"conda:typos-lsp" = "latest"
"conda:universal-ctags" = "latest"
"conda:vim" = "latest"
"core:deno" = "latest"
"core:go" = "latest"
"core:java" = "latest"
"core:node" = "latest"
"core:rust" = "latest"
"github:babashka/babashka" = "latest"
"github:candid82/joker" = "latest"
"github:jgm/pandoc" = "latest"
"github:microsoft/aspire" = "latest"
"github:odin-lang/Odin" = "latest"
"github:prefix-dev/pixi" = "latest"
"npm:prettier" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"vfox:jdx/vfox-clojure" = "latest"
"vfox:namvnn/vfox-mole" = "latest"
