[colors.primary]
foreground        = "#FFFFFF"
background        = "#000000"

[colors.normal]
black             = "#212121"
red               = "#FF0000"
green             = "#00FF00"
yellow            = "#FFFF00"
blue              = "#0000FF"
magenta           = "#FF00FF"
cyan              = "#00FFFF"
white             = "#FFFFFF"
