[directory]
truncation_length = 8
format = "\n[$path]($style)[$read_only]($read_only_style) "
truncation_symbol = "…/"
truncate_to_repo = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true