[note]
language = "en"
default-title = "untitled"
filename = "{{slug title}}"
template = "default.md"

[extra]
author = "Nam Nguyen"

[group.daily]
paths = ["_daily"]

[group.daily.note]
filename = "{{format-date now}}"
template = "daily.md"

[format.markdown]
link-format = "markdown"

[filter]
recent = "--sort modified- --modified-after 'last two weeks'"

[alias]
bl     = 'zk list --link-to "$@"'
conf   = '$EDITOR "$HOME/.config/zk/config.toml"'
daily  = 'zk new --no-input "$ZK_NOTEBOOK_DIR/_daily"'
ed     = 'zk edit --interactive "$@"'
edl    = 'zk edit --limit 1 --sort modified- "$@"'
inline = 'zk list --quiet --format {{path}} --delimiter , "$@"'
log    = 'zk list --quiet --format path --delimiter0 "$@" | xargs -0 git log --patch --'
ls     = 'zk list --interactive "$@"'
lucky  = 'zk edit --sort random --limit 1'
n      = 'zk new "$@"'
nt     = 'zk new --title "$*"'
paths  = "zk list --quiet --format \"'{{path}}'\" --delimiter ' ' $@"
recent = "zk edit --sort modified- --modified-after 'last two weeks' --interactive"
wc     = "zk list --format '{{word-count}}\t{{path}}' --sort word-count $@"

[lsp.completion]
note-label = "{{path}}"
note-filter-text = "{{title}} {{path}}"
