[[colors.indexed_colors]]
color = "#ffe37e"
index = 16

[[colors.indexed_colors]]
color = "#e06c75"
index = 17

[colors.bright]
black = "#7f8c98"
blue = "#84cee4"
cyan = "#59f0ff"
green = "#58cd8b"
magenta = "#b8a1e3"
red = "#e06c75"
white = "#fdebc3"
yellow = "#ffe37e"

[colors.cursor]
cursor = "#abb2bf"
text = "#0e171c"

[colors.normal]
black = "#393b44"
blue = "#61afef"
cyan = "#63cdcf"
green = "#97c374"
magenta = "#c678dd"
red = "#c94f6d"
white = "#dfdfe0"
yellow = "#dbc074"

[colors.primary]
background = "#0e171c"
foreground = "#abb2bf"
