[colors.primary]
foreground = "#000000"
background = "#FFFFFF"

[colors.normal]
black      = "#000000"
white      = "#FFFFFF"

[colors.cursor]
cursor     = "#000000"
text       = "#FFFFFF"

[colors.selection]
background = "#000000"
text       = "#FFFFFF"
