[colors.primary]
foreground = "#000000"
background = "#E0E2E9"

[colors.normal]
black      = "#FFFFFF"
red        = "#CC0000"
green      = "#00CC00"
yellow     = "#CCCC00"
blue       = "#0000CC"
magenta    = "#CC00CC"
cyan       = "#00CCCC"
white      = "#000000"

[colors.cursor]
cursor     = "#FFFFFF"
text       = "#000000"

[colors.selection]
background = "#FFFFFF"
text       = "#000000"
