[colors.primary]
foreground = "#000000"
background = "#FFFFFF"

[colors.normal]
black      = "#000000"
red        = "#CC0000"
green      = "#00CC00"
yellow     = "#CCCC00"
blue       = "#0000CC"
magenta    = "#CC00CC"
cyan       = "#00CCCC"
white      = "#FFFFFF"

[colors.cursor]
cursor     = "#000000"
text       = "#FFFFFF"

[colors.selection]
background = "#000000"
text       = "#FFFFFF"
