[colors.primary]
foreground = "#FFFFFF"
background = "#3A3A3A"

[colors.normal]
black      = "#000000"
red        = "#FF0000"
green      = "#00FF00"
yellow     = "#FFFF00"
blue       = "#0000FF"
magenta    = "#FF00FF"
cyan       = "#00FFFF"
white      = "#FFFFFF"
