require("namnguyen.general")
require("namnguyen.plugins")
require("namnguyen.remap")
require("namnguyen.cursor")
require("namnguyen.execution")
require("namnguyen.templates")
require("namnguyen.autocmd")
