[font]
size = 17
offset = { y = 1 }
normal = { family = "Fixedsys Excelsior", style = "Regular" }
bold = { family = "Fixedsys Excelsior", style = "Regular" }
italic = { family = "Fixedsys Excelsior", style = "Regular" }
bold_italic = { family = "Fixedsys Excelsior", style = "Regular" }
